import {phases,slides} from './content.js';
const main=document.querySelector('main');
let done=[],priority=false,storageOK=true;
try {const saved=JSON.parse(localStorage.getItem('security-progress-v1')||'[]'); if(Array.isArray(saved)) done=saved.filter(x=>Number.isInteger(x)&&x>=0&&x<slides.length);}catch{storageOK=false;}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let mode='map',index=0;
const go=(m,i)=>{location.hash=`/${m}/${i}`;};
const btn=(text,action,cls='')=>`<button class="${cls}" ${action}>${text}</button>`;
function render(){const match=location.hash.match(/^#\/(map|slide)\/(\d+)$/); mode=match?.[1]||'map';index=Math.min(Number(match?.[2]||0),mode==='map'?8:15);const p=phases[mode==='map'?index:slides[index].phase];
document.querySelector('#map-link').href=`#/map/${p.id}`; document.querySelector('#slide-link').href=`#/slide/${mode==='slide'?index:p.slide}`;
for(const m of ['map','slide']){document.querySelector(`#${m}-link`).classList.toggle('active',mode===m);document.querySelector(`#${m}-link`).setAttribute('aria-current',mode===m?'page':'false');}
document.title=`${mode==='map'?'資安學習地圖':slides[index].title} · Security Fieldnotes`;
const progress=Math.round(done.length/16*100); document.querySelector('#progress').innerHTML=`<b>${String(progress).padStart(2,'0')}%</b> <progress max="16" value="${done.length}" aria-label="學習進度"></progress> ${done.length} / 16 頁已完成 <small>${storageOK?'僅儲存在此瀏覽器':'本次進度無法持久儲存'}</small>`;
const side=`<aside class="detail ${p.color}"><span class="eyebrow">FIELD NOTE / ${String(p.id+1).padStart(2,'0')}</span><h2>${p.title}</h2><p>${p.subtitle}</p><hr><h3>你會學到</h3><p>${p.goal}</p><h3>動手練習</h3><p>${mode==='map'?p.exercise:slides[index].task}</p>${mode==='map'?`<a class="primary" href="#/slide/${p.slide}">進入這一章 <span>↗</span></a>`:btn(done.includes(index)?'✓ 已完成這一頁':'標記這一頁完成','data-complete',done.includes(index)?'completed':'primary')}${mode==='slide'&&slides[index].source?`<a class="source" href="${slides[index].source}" target="_blank" rel="noopener noreferrer">延伸閱讀 · 官方文件 ↗</a>`:''}<div class="side-note">${mode==='map'?(index===0?'起點：先認識資產與影響。':`建議先備：${phases[index-1].title}`):'理解概念 → 做一次練習 → 留下證據'}</div></aside>`;
if(mode==='map')main.innerHTML=`<section class="intro"><div><span class="eyebrow">YOUR SECURITY LEARNING ATLAS</span><h1>把概念連起來，<em>走出自己的學習路徑。</em></h1><p>從資安基礎到安全工程。點選一個節點，開始理解與練習。</p></div><div class="path-switch" role="group" aria-label="學習路徑">${btn('完整路徑','data-path="all" aria-pressed="'+!priority+'"',!priority?'selected':'')}${btn('Web 開發者優先','data-path="web" aria-pressed="'+priority+'"',priority?'selected':'')}</div></section><div class="workspace"><section class="map-paper" aria-label="九階段學習地圖"><div class="map-caption"><span>THE LEARNING PATH</span><span>01 — 09 / 自由探索</span></div><div class="nodes">${phases.map((q,i)=>`<button class="node ${q.color} ${index===i?'chosen':''} ${priority&&i<3?'muted':''}" data-node="${i}" aria-pressed="${index===i}"><span class="node-top"><span class="number">${String(i+1).padStart(2,'0')}</span><span>${done.includes(q.slide)?'✓ 已開始完成':priority&&i===3?'優先起點':i<4?'建立基礎':i<6?'觀察與實驗':'帶回開發'}</span><span>↗</span></span><h2>${q.title}</h2><p>${q.subtitle}</p><small>${q.tags}</small></button>`).join('')}</div><div class="map-legend"><span>● 目前選取</span><span>${priority?'加深節點：Web 開發者優先路徑':'編號表示建議順序，不限制閱讀'}</span><a href="#/slide/0">從第一頁開始 →</a></div></section>${side}</div>`;
else {const s=slides[index];main.innerHTML=`<section class="slide-heading"><a href="#/map/${p.id}">← 返回學習地圖</a><span>${p.title} / ${String(index+1).padStart(2,'0')} OF 16</span></section><div class="slide-workspace"><nav class="rail" aria-label="階段導覽">${phases.map(q=>`<a class="${q.id===p.id?'current':''}" href="#/slide/${q.slide}"><b>${String(q.id+1).padStart(2,'0')}</b><span>${q.title}</span></a>`).join('')}</nav><article class="slide-paper ${p.color}"><span class="eyebrow">CHAPTER ${String(p.id+1).padStart(2,'0')} / ${p.tags}</span><h1 tabindex="-1">${s.title}</h1><p class="lead">${s.intro}</p><div class="concepts">${s.items.map(([a,b],j)=>`<section class="concept"><span class="concept-no">0${j+1}</span><div><h2>${esc(a)}</h2><p class="${b.includes('\n')?'code':''}">${esc(b)}</p></div></section>`).join('')}</div><div class="slide-controls">${btn('← 上一頁',`data-prev ${index===0?'disabled':''}`)}<span>${String(index+1).padStart(2,'0')} <span class="slash">/</span> 16</span>${index===15?'<a class="primary" href="#/map/8">回到地圖 ↗</a>':btn('下一頁 →','data-next','primary')}</div></article>${side}</div>`;}
main.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>go('map',+b.dataset.node));main.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>{priority=b.dataset.path==='web';render();});main.querySelector('[data-prev]')?.addEventListener('click',()=>go('slide',index-1));main.querySelector('[data-next]')?.addEventListener('click',()=>go('slide',index+1));main.querySelector('[data-complete]')?.addEventListener('click',()=>{done=done.includes(index)?done.filter(x=>x!==index):[...done,index];save();render();});}
function save(){try{localStorage.setItem('security-progress-v1',JSON.stringify(done));}catch{storageOK=false;}}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
document.querySelector('#reset').onclick=()=>{if(confirm('清除這個瀏覽器中的學習進度？')){done=[];save();render();}};
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(mode==='slide'){if(e.key==='ArrowRight'&&index<15){e.preventDefault();go('slide',index+1);}if(e.key==='ArrowLeft'&&index>0){e.preventDefault();go('slide',index-1);}if(e.key==='Escape')go('map',slides[index].phase);}});
let start; main.addEventListener('touchstart',e=>{start=[e.changedTouches[0].clientX,e.changedTouches[0].clientY];},{passive:true}); main.addEventListener('touchend',e=>{if(!start||mode!=='slide')return;const dx=e.changedTouches[0].clientX-start[0],dy=e.changedTouches[0].clientY-start[1];if(Math.abs(dx)>90&&Math.abs(dy)<50){if(dx<0&&index<15)go('slide',index+1);if(dx>0&&index>0)go('slide',index-1);}start=null;},{passive:true});render();
