import assert from 'node:assert/strict';
import {initialConfig,evaluate,accepted,replay} from '../src/labs/workbench.ts';
export function solve(id,round){const c=initialConfig(id,round);if(round>0){if(id===0)c.placements={access:'api',failover:'recovery'};if(id===7)c.placements={owner:'upload',budget:'parser',fields:'data'};if(id===3)c.placements={session:'before',owner:'before'};if(id===4)c.placements={param:'sql',encode:'html'};if(id===6){c.placements={owner:'shared',state:'shared',fields:'shared',redact:'shared'};c.routes={api:'shared',batch:'shared',worker:'shared'};}if(id===5){if(round===1)c.order=['authorize','write','notify'];else{c.transaction=true;c.afterCommit=true;}}if(id===8){c.tests=['legal','owner','state','side'];c.placements={signal:'denied',person:'oncall',action:'investigate'};}}if(id===1){c.known=['version','exposure','impact'];c.priority=round===0?['A','B']:['B','A'];}if(id===2){c.environment=round===0?'test':'next';c.log=c.environment;c.commands=['pwd','whoami','version','cat logs/app.log'];}return c;}
for(const id of [0,7,1,3,4,6,2,5,8])for(let round=0;round<3;round++){const c=solve(id,round),r=evaluate(id,c,round);assert.ok(accepted(id,round,c,r),`id=${id} round=${round} ${JSON.stringify(r)}`);assert.ok(r.events.length);assert.ok(r.checks.length);}
let c=solve(3,1);c.placements.owner='after';assert.equal(evaluate(3,c,1).signature,'exposed');assert.equal(evaluate(3,c,1).safe,false);c.placements.owner='client';assert.equal(evaluate(3,c,1).signature,'exposed');
c=solve(7,1);c.placements.owner='parser';assert.equal(evaluate(7,c,1).safe,false);assert.equal(evaluate(7,c,1).signature,'exposed');
c=solve(6,1);c.routes.batch='direct';assert.equal(evaluate(6,c,1).signature,'exposed');c.routes.batch='shared';c.routes.worker='direct';assert.equal(evaluate(6,c,1).safe,false);
c=solve(4,1);c.placements.encode='sql';assert.equal(evaluate(4,c,1).safe,false);c.placements={validate:'input'};assert.equal(evaluate(4,c,1).safe,false);
c=solve(5,2);c.afterCommit=false;assert.equal(replay(c).written,false);assert.equal(replay(c).notified,true);assert.equal(evaluate(5,c,2).safe,false);c.afterCommit=true;c.transaction=false;assert.equal(replay(c).written,true);assert.equal(replay(c).notified,false);assert.equal(evaluate(5,c,2).safe,false);
c=solve(1,1);c.known=['version','exposure'];assert.equal(evaluate(1,c,1).safe,false);c.known.push('impact');c.priority=['A','B'];assert.equal(evaluate(1,c,1).safe,false);
c=solve(2,2);c.environment='prod';assert.equal(evaluate(2,c,2).safe,false);c.environment='next';c.log='prod';assert.equal(evaluate(2,c,2).safe,false);
c=solve(8,2);c.tests=['legal','state'];assert.equal(evaluate(8,c,2).safe,false);c.tests=['legal','state','side'];c.fault='none';assert.equal(accepted(8,2,c,evaluate(8,c,2)),false);
c=solve(0,2);c.placements.failover='api';assert.equal(evaluate(0,c,2).safe,false);
console.log('PASS 27 workbench tasks; wrong placement, bypass paths, partial protection, rollback/notification, environment and coverage counterexamples');
