import type {UnitId} from './model';
export type Control={key:string;label:string;type:'toggle'|'select';options?:{label:string;value:string}[]};
export type Unit={id:UnitId;slug:string;title:string;question:string;teaching:string;transfer:string;controls:Control[]};
export const units:Unit[]=[
{id:1,slug:'objectives',title:'什麼不能發生？',question:'功能正常之外，哪些結果不可接受？',teaching:'線上文件分享系統',transfer:'案件系統',controls:[{key:'event',label:'事件',type:'select',options:[{label:'陌生人讀取',value:'read'},{label:'Viewer 修改',value:'edit'},{label:'服務中斷',value:'outage'}]},{key:'policy',label:'文件政策',type:'select',options:[{label:'私人',value:'private'},{label:'公開',value:'public'}]}]},
{id:2,slug:'risk',title:'有漏洞，就一定要先修嗎？',question:'從漏洞到優先處理，中間缺哪些 evidence？',teaching:'兩個 Web Services',transfer:'Self-hosted dependency',controls:[{key:'affected',label:'版本受影響',type:'toggle'},{key:'reachable',label:'可從外部到達',type:'toggle'},{key:'kev',label:'已有實際利用訊號',type:'toggle'},{key:'mitigation',label:'已有有效 mitigation',type:'toggle'}]},
{id:3,slug:'trust',title:'登入成功，為什麼還不能直接相信？',question:'誰可以對哪個 resource 做什麼？',teaching:'線上文件分享系統',transfer:'Sim-sik / 案件系統',controls:[{key:'authorizeBefore',label:'在讀寫前做資源授權',type:'toggle'},{key:'serviceScope',label:'Service 權限',type:'select',options:[{label:'廣泛',value:'broad'},{label:'最小必要',value:'scoped'}]}]},
{id:4,slug:'interpretation',title:'這串文字到了下一站，會被當成什麼？',question:'資料在哪一步取得新的語意？',teaching:'簡單電商 Web App',transfer:'VocaScript / 文件引擎',controls:[{key:'sink',label:'解讀環境',type:'select',options:[{label:'SQL',value:'sql'},{label:'HTML',value:'html'},{label:'Path',value:'path'},{label:'Process API',value:'process'}]},{key:'parameterized',label:'SQL 使用參數化',type:'toggle'},{key:'safeOutput',label:'HTML 使用安全輸出',type:'toggle'},{key:'safePath',label:'Path 限制目的地',type:'toggle'},{key:'structuredApi',label:'Process 使用 structured API',type:'toggle'}]},
{id:5,slug:'blast-radius',title:'先假設 API 已經失守',question:'從這裡還能走多遠？',teaching:'三層 SaaS',transfer:'Multi-service VM',controls:[{key:'separateIdentity',label:'Service 使用獨立 identity',type:'toggle'},{key:'segmented',label:'Network segmentation',type:'toggle'},{key:'dbScope',label:'DB 權限',type:'select',options:[{label:'Admin',value:'admin'},{label:'Read only',value:'read'}]}]},
{id:6,slug:'supply-chain',title:'「有加密」到底保護了哪一種情況？',question:'資料、Secret、Dependency 與 Artifact 怎麼建立信任？',teaching:'小型電商 CI/CD',transfer:'自動發文 / GitHub Actions',controls:[{key:'threat',label:'Threat',type:'select',options:[{label:'硬碟遺失',value:'disk'},{label:'Application compromised',value:'app'}]},{key:'diskEncryption',label:'Disk encryption',type:'toggle'},{key:'secretRevoked',label:'撤銷已洩漏 Secret',type:'toggle'},{key:'artifactVerified',label:'驗證 Artifact provenance',type:'toggle'}]},
{id:7,slug:'evidence',title:'AI 說修好了，我們憑什麼相信？',question:'不同 evidence source 能證明什麼？',teaching:'Synthetic Web API',transfer:'AI-assisted development workflow',controls:[{key:'sast',label:'Semgrep-like SAST',type:'toggle'},{key:'sca',label:'Dependency scan',type:'toggle'},{key:'secrets',label:'Secret scan',type:'toggle'},{key:'negativeTest',label:'Authorization negative test',type:'toggle'},{key:'correlation',label:'Runtime correlation ID',type:'toggle'}]},
{id:8,slug:'recovery',title:'真的出事了，現在先做什麼？',question:'怎麼限制影響並重新建立可信狀態？',teaching:'Deployment credential incident',transfer:'Self-hosted service',controls:[{key:'revoke',label:'撤銷 Credential',type:'toggle'},{key:'isolate',label:'隔離 Service',type:'toggle'},{key:'rotate',label:'輪替 downstream secrets',type:'toggle'},{key:'trustedArtifact',label:'重新部署可信 Artifact',type:'toggle'},{key:'restore',label:'驗證資料 Restore',type:'toggle'}]}
];
export const bySlug:Record<string,Unit>=Object.fromEntries(units.map(u=>[u.slug,u]));
