<script setup lang="ts">
import {computed,ref,watch,nextTick} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {finalDefaults,incidents,evaluateFinal} from './final-model';
import type {Control} from './course';
import type {Value} from './model';
import ControlsV2 from './ControlsV2.vue';
import SystemGraph from './SystemGraph.vue';
const route=useRoute(),router=useRouter();
const state=ref({...finalDefaults}),before=ref({...finalDefaults}),compare=ref(false),pulse=ref(0);
const step=computed(()=>Math.min(5,Math.max(0,Math.trunc(Number(route.query.step))||0)));
const reached=computed(()=>Math.max(step.value,Math.min(5,Math.max(0,Math.trunc(Number(route.query.reached))||0))));
const incident=computed(()=>incidents[step.value]);
const result=computed(()=>evaluateFinal(state.value,reached.value));
const beforeResult=computed(()=>evaluateFinal(before.value,reached.value));
const labels:Record<string,string>={resourceCheck:'每次讀取前核對人與文件的允許條件',safePreview:'預覽固定結構，外部值只作資料',advisoryChecked:'已核對版本與使用路徑',versionAffected:'目前版本受此通知影響',dependencyUsed:'實際路徑使用此套件',patched:'改到不受此通知影響版本',separateWorker:'Worker 不共用外部發布 credential',workerRoute:'Worker 到資料／儲存空間 route 可達',workerRevoked:'撤銷失守的工作身分',fields:'事件紀錄含時間／身分／資源／操作',interaction:'跨服務紀錄共用 interaction ID',bulkRule:'為大量存取建立 alert rule',deployRevoked:'撤銷外洩部署 token',provenance:'核對 artifact 來源與摘要',knownArtifact:'重新部署已核對來源的 artifact',rotate:'切換下游秘密並撤銷舊副本',restore:'還原資料 snapshot',restoreVerified:'驗證還原後完整性與時間點',isolate:'隔離目前執行服務',resume:'請求恢復服務',sast:'取得課程規則分析結果',behaviorTest:'執行 API 物件行為 test',dependencyScan:'取得依賴版本掃描結果',secretScan:'取得 fake token 掃描結果'};
const selections:Record<string,{label:string;options:string[][]}>={asset:{label:'需要保護的東西',options:[['customer documents','Customer documents'],['deployment capability','Deployment capability'],['service availability','Service availability']]},objective:{label:'不可接受的結果',options:[['read','私人內容被其他人讀到'],['write','內容被未允許的人修改'],['availability','必要時無法使用服務']]},sharing:{label:'文件公開範圍',options:[['private','只給指定協作者'],['public','允許公開讀取']]},workerScope:{label:'Worker 的物件能力',options:[['all','讀／改／刪'],['read','只讀指定物件'],['none','不能取得物件']]},ciScope:{label:'CI identity 的能力',options:[['write','可發布 artifact'],['read','只讀 build 資料']]},domain:{label:'換一個熟悉的 domain（仍是合成模型）',options:[['collaboration SaaS','Collaboration SaaS'],['Sim-sik','Sim-sik'],['案件系統','案件系統'],['Podcast hosting','Podcast hosting'],['VocaScript','VocaScript'],['自動發文','自動發文'],['multi-repo deployment','Multi-repo deployment']]}};
const availableKeys=computed(()=>[...new Set(incidents.slice(0,reached.value+1).flatMap(i=>i.keys))]);
const controls=computed<Control[]>(()=>availableKeys.value.map(key=>selections[key]?{key,label:selections[key].label,type:'select',options:selections[key].options.map(([value,label])=>({value,label}))}:{key,label:labels[key],type:'toggle'}));
watch(()=>route.fullPath,()=>{state.value={...finalDefaults};try{const raw=JSON.parse(String(route.query.state||'null'));if(raw&&typeof raw==='object')for(const k of Object.keys(finalDefaults))if(typeof raw[k]===typeof finalDefaults[k])state.value[k]=raw[k];}catch{/* Invalid URL resets synthetic state. */}},{immediate:true});
async function change(key:string,value:Value){state.value={...state.value,[key]:value};pulse.value++;await router.replace({query:{...route.query,state:JSON.stringify(state.value)}});}
async function go(n:number){await router.push({query:{step:String(n),reached:String(Math.max(reached.value,n)),state:JSON.stringify(state.value)}});pulse.value++;await nextTick();document.querySelector<HTMLElement>('h1')?.focus();}
async function reset(){compare.value=false;await router.replace({query:{}});pulse.value++;}
function snapshot(){before.value={...state.value};compare.value=true;}
</script>
<template><section class="v2-lesson v2-final"><nav class="v2-top" aria-label="課程導覽"><RouterLink to="/v2">← 課程入口</RouterLink><span>INTEGRATED TRANSFER · {{step+1}}／6</span></nav><h1 tabindex="-1">{{incident.title}}</h1><p class="v2-question">{{incident.question}}</p><p class="v2-synthetic">{{state.domain}} · 同一個 deterministic synthetic collaboration system；事件依序加入，前一輪設定保留。已加入第 {{Math.min(reached+1,5)}} 個變化；返回先前設定不移除已發生的事件。</p><nav class="v2-stages" aria-label="事件時間線"><button v-for="(item,i) in incidents" :key="item.title" :aria-current="i===step?'step':undefined" @click="go(i)">{{i+1}}. {{item.title}}</button></nav><div class="v2-toolbar"><button @click="snapshot">保留比較起點</button><button v-if="compare" @click="compare=false">關閉比較</button><button @click="pulse++">重播路徑</button><button @click="reset">整個情境重新開始</button></div><div class="v2-workbench"><section class="v2-control-panel"><h2>改變系統事實</h2><ControlsV2 :controls="controls" :values="state" @change="change"/></section><section class="v2-canvas"><h2>觀察哪些資源与能力改變</h2><SystemGraph :result="result" :pulse="pulse" :before="compare?beforeResult:undefined"/><dl class="v2-metrics"><template v-for="(value,key) in result.metrics" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></template></dl></section></div><section class="v2-evidence"><h2>Evidence／未涵蓋的範圍</h2><p v-if="!result.evidence.length">先提出要驗證的 claim，再選可提供依據的工具。沒有結果不代表安全。</p><div v-for="e in result.evidence" :key="e.id" class="v2-evidence-row" :data-evidence="e.id"><strong>{{e.source}} · {{e.claim}}</strong><p>{{e.observation}}</p><small>{{e.scope}}</small></div></section><details class="v2-assumptions"><summary>合成系統的明示假設</summary><p>圖上 Browser 的要求固定為改 document ID，取得另一位擁有者文件；預覽固定含非真實 payload 的 STRUCTURE_MARKER。標成「失守身分」或「未知 runtime」的連線只表示 incident 路徑，没有 active attack path 不代表合法工作不能進行。API policy 只約束正常 API request；失守 Worker 繼承現有 credential、route 與 scope。公開政策只允許讀取。已執行的未知 artifact 不會因部署 token 撤銷而停止。</p><p>隔離會使協作不可用。下游輪替包含 consumer 切換與舊值撤銷；資料 restore 需另驗證完整性與時間點。產物来源匹配不是無漏洞證明。恢復 gate 只驗證本畫面列出的事件路徑。</p><p>{{result.limit}}</p></details><section v-if="step===5" class="v2-transfer"><h2>用圖和依據說明你的判斷</h2><p>你保護什麼？哪些假設需要重新查證？每個控制在哪裡？一層失守後能走多遠？哪些 evidence 支持恢復？還不知道什麼？</p><p>熟悉 domain 的選項只改情境名稱，沒有載入實際專案資料。不要把本模型當作該專案現況；可和 AI 自行建立其真實架構與需求。不儲存個人作答、不提供章節答案提示。</p></section><footer class="v2-navigation"><button :disabled="step===0" @click="go(step-1)">← 上一個變化</button><button v-if="step<5" @click="go(step+1)">加入下一個變化 →</button><RouterLink v-else to="/v2">回課程入口</RouterLink></footer></section></template>
