<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {phases,slides} from '../content/learning';
import HttpLesson from './HttpLesson.vue'; import UiIcon from './UiIcon.vue';
const route=useRoute(),router=useRouter();const index=computed(()=>Number(route.params.index));const slide=computed(()=>slides[index.value]);const phase=computed(()=>phases[slide.value.phase]);
const selected=ref(0);watch(index,()=>selected.value=0);
function move(step:number){const next=index.value+step;if(next>=0&&next<slides.length)router.push(`/slide/${next}`);}
function keydown(e:KeyboardEvent){if(e.altKey||e.ctrlKey||e.metaKey||(e.target instanceof HTMLElement&&(e.target.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))))return;if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}if(e.key==='Escape')router.push(`/map/${phase.value.id}`);}
onMounted(()=>document.addEventListener('keydown',keydown));onUnmounted(()=>document.removeEventListener('keydown',keydown));
let start:[number,number]|undefined;
function touchstart(e:TouchEvent){if(e.touches.length!==1){start=undefined;return;}start=[e.touches[0].clientX,e.touches[0].clientY];}
function touchend(e:TouchEvent){if(!start)return;const dx=e.changedTouches[0].clientX-start[0],dy=e.changedTouches[0].clientY-start[1];start=undefined;if(Math.abs(dx)>90&&Math.abs(dy)<50)move(dx<0?1:-1);}
</script>
<template><section class="slide-heading"><span>{{phase.title}} <span class="crumb">›</span> {{String(index+1).padStart(2,'0')}} / 16</span></section><section class="lesson-title"><h1>{{slide.title}}</h1><p>{{slide.intro}}</p></section><div @touchstart.passive="touchstart" @touchend.passive="touchend" @touchcancel="start=undefined"><HttpLesson v-if="index===6"/><div v-else class="lesson-grid"><article class="lesson-main concept-lesson"><div class="concept-steps"><button v-for="([title,text],i) in slide.items" :key="title" class="concept" :class="{selected:selected===i}" :aria-pressed="selected===i" @click="selected=i"><span class="step-number">{{String(i+1).padStart(2,'0')}}</span><UiIcon :name="(['globe','shield','database'] as const)[i]" :size="48"/><h2>{{title}}</h2><p>{{text.split('。')[0]}}。</p></button></div><div class="selected-concept" aria-live="polite"><span>概念 {{selected+1}} / {{slide.items.length}}</span><h2>{{slide.items[selected][0]}}</h2><p class="concept-text">{{slide.items[selected][1]}}</p></div><details class="practice"><summary><UiIcon name="lab"/><span>動手練習<small>把這個概念連回自己的測試環境。</small></span><UiIcon name="right" :size="18"/></summary><p>{{slide.task}}</p></details></article><aside class="inspector learning-note"><span class="eyebrow">LEARNING NOTES / {{String(phase.id+1).padStart(2,'0')}}</span><h2>{{phase.title}}</h2><p>{{phase.subtitle}}</p><h3>你會學到</h3><p>{{phase.goal}}</p><h3>這一頁的練習</h3><p>{{slide.task}}</p><a v-if="slide.source" class="source" :href="slide.source" target="_blank" rel="noopener noreferrer">官方延伸閱讀 <UiIcon name="right" :size="16"/></a><div class="takeaway"><UiIcon name="info"/><p>點選左側概念，逐項閱讀、觀察，再用自己的話解釋。</p></div></aside></div></div></template>