import type {DeepLab} from './deep';
import type {Outcome,Control} from './model';
const c=(key:string,label:string):Control=>({key,label,type:'check',value:false});
const s=(key:string,label:string,options:[string,string][]):Control=>({key,label,type:'select',value:options[0]![0],options});
function result(safe:boolean,rows:string[][],summary:string,steps:[string,string][]):Outcome{return {signature:safe?'safe':'gap',title:safe?'整合驗證符合指定需求':'整合驗證仍有缺口',summary,trace:steps,columns:['項目','觀察結果','判定'],rows,lesson:'以這組證據支持指定需求，同時記錄尚未驗證的條件。',tone:safe?'good':'bad'};}
export const missionLabs:DeepLab[]=[
{title:'替案件文件上傳建立安全說明',principle:'把資產、資料邊界、安全需求與處理優先序連成一份可以解釋的決策。',checkpoint:'合法負責人送來的文件，還有哪些條件不能只靠登入確認？',controls:[s('asset','要保護的資產',[['file','只有原始檔案'],['all','檔案、案件欄位與解析服務']]),c('owner','需求：上傳者必須對案件有權限'),c('fields','需求：入庫前排除未允許欄位'),c('resource','需求：限制解析資源'),s('priority','優先處理',[['score','只依嚴重度分數'],['context','依受影響版本、暴露、利用與影響']])],predictions:[['gap','仍有資產、邊界或優先序缺口'],['safe','本輪指定風險都有對應需求']],cases:[{title:'看見整條資料流',story:'文件從上傳、內部儲存到解析入庫。部署中的解析器版本受影響、對外可觸及，且有已知利用訊號。',target:'觀察只保護原始檔案會漏掉什麼。',hint:'先使用預設規劃，查看未涵蓋的資產。',expected:'gap'},{title:'完成需求與決策',story:'沿同一份文件資料流補齊規劃，將已知利用與業務影響納入排序。',target:'為指定資產與邊界建立完整規劃。',hint:'每個需求都要對應資料流的一段。',expected:'safe'},{title:'替換成批次文件',story:'合法承辦人批次送入大量文件，內容仍來自外部。組織需要保持解析服務可用，入庫欄位也仍受限。',target:'確認新入口與批次規模仍在安全需求範圍。',hint:'',expected:'safe'}],limit:'此任務驗證規劃涵蓋範圍，不執行真實檔案解析或漏洞掃描。',run(v,r){const rows=[['資產範圍',v.asset==='all'?'涵蓋資料與服務':'漏掉下游資料與服務',v.asset==='all'?'通過':'缺口'],['上傳邊界',v.owner?'核對案件權限':'只有登入',v.owner?'通過':'缺口'],['解析邊界',v.resource?'限制資源':'可用性未規劃',v.resource?'通過':'缺口'],['寫入邊界',v.fields?'限制欄位':'欄位可直接入庫',v.fields?'通過':'缺口'],['風險決策',v.priority==='context'?'優先處理有利用條件的解析器':'僅依分數，忽略部署',v.priority==='context'?'通過':'缺口']];return result(rows.every(x=>x[2]==='通過'),rows,r===2?'新入口仍需要同一組安全需求。':'檢查資產、三個邊界與修補理由。',[['資料來源',r===2?'批次文件，合法使用者':'單份 PDF，合法使用者'],['資料流','Upload → Storage → Parser → Database'],['需求對照','檢查每個資產與邊界的需求']]);}},
{title:'保護單筆修改與批次匯入',principle:'共用需求必須涵蓋不同入口，兼顧合法操作、違規拒絕及日誌。',checkpoint:'只有 API 層有檢查時，批次匯入會經過它嗎？',controls:[c('api','單筆 API 核對歸屬'),c('service','共用寫入服務核對歸屬'),c('state','共用服務限制結案修改'),c('fields','共用服務限制允許欄位'),c('redact','日誌遮蔽 Session')],predictions:[['gap','至少一條路徑違反需求'],['safe','本輪指定路徑符合需求']],cases:[{title:'辨識不同入口',story:'Alice 可更新自己的 open 案件，但不得更新 Bob 的案件；任何入口都不得修改 closed 案件。日誌不得包含 Session。',target:'找出未受保護的入口。',hint:'預設皆關閉，先查看哪個反例失敗。',expected:'gap'},{title:'配置共用規則',story:'單筆與批次路徑共用案件寫入服務。請在合適位置放置檢查。',target:'合法操作可成功，違規操作被拒絕，日誌不洩漏憑證。',hint:'規則要覆蓋所有寫入路徑。',expected:'safe'},{title:'背景同步也會寫入',story:'新增背景同步入口；外部資料含未允許的 internalRole 欄位。它經過共用寫入服務。',target:'讓新入口遵守同一套限制。',hint:'',expected:'safe'}],limit:'固定案例驗證，不涵蓋所有狀態轉移、租戶關係或並行寫入。',run(v,r){const rows=[['合法負責人修改','200，成功更新','通過'],['單筆越權',v.api||v.service?'403，未改動':'200，錯誤修改',v.api||v.service?'通過':'失敗'],['批次越權',v.service?'403，未改動':'200，錯誤修改',v.service?'通過':'失敗'],['已結案修改',v.state?'拒絕，未改動':'允許修改',v.state?'通過':'失敗'],['未允許欄位',v.fields?'拒絕寫入':'internalRole 寫入',v.fields?'通過':'失敗'],['稽核日誌',v.redact?'Session=[REDACTED]':'Session=demo',v.redact?'通過':'失敗']];if(r===2)rows.push(['背景同步',v.service&&v.fields&&v.state?'套用所有共用規則':'至少一條共用規則缺少',v.service&&v.fields&&v.state?'通過':'失敗']);return result(rows.every(x=>x[2]==='通過'),rows,'每一列都是具體入口、操作與可觀察結果。',[['路徑',r===2?'單筆／批次／背景同步':'單筆／批次'],['共用服務',v.service?'核對資源歸屬':'缺少共用歸屬檢查'],['驗證','比對資料變化與日誌']]);}},
{title:'接手有缺陷的版本並留下回歸證據',principle:'先定位正確環境，再重現副作用、驗證修補，最後建立會抓到回歸的測試。',checkpoint:'只測回應碼，能抓到「403 但通知已寄出」嗎？',controls:[s('env','驗證環境與版本',[['old','test-vm v1'],['target','test-vm v2（本次目標）']]),c('repair','將授權檢查移到所有副作用之前'),c('cross','回歸測試：跨帳號請求被拒絕'),c('effects','回歸測試：拒絕時資料與通知皆不變'),c('monitor','監控：異常拒絕與資料改動有請求識別'),c('response','應變：指定處理人與調查／回復動作')],predictions:[['gap','修補或持續驗證仍缺少證據'],['safe','本輪修補、回歸與營運要求都有證據']],cases:[{title:'找出證據缺口',story:'v2 回傳 403，但案件已改動並寄出通知。你手上的成功日誌來自 v1。',target:'辨識目前無法支持發布的證據。',hint:'先跑預設方案，檢查環境與副作用。',expected:'gap'},{title:'驗證修補與回歸',story:'在 test-vm v2 重現問題，配置修補；用刻意移除修補的版本確認測試會失敗。',target:'補齊可重現的修補與持續驗證證據。',hint:'同時測拒絕回應及實際副作用。',expected:'safe'},{title:'只改壞通知順序',story:'新改動保持 403 和資料回滾，但提前寄出通知。需要確認這種回歸也會被抓到。',target:'使用副作用反例，並留下監控與處理方式。',hint:'',expected:'safe'}],limit:'模型只注入指定缺陷；監控與應變選項表示已規劃，沒有建立真實告警。',run(v,r){const rows=[['證據來源',v.env==='target'?'test-vm v2':'舊版證據，不適用',v.env==='target'?'通過':'缺口'],['修補結果',v.repair?'403、資料未變、通知 0':'403、資料或通知已改變',v.repair?'通過':'缺口'],['刻意回歸測試',r===2?(v.effects?'通知反例失敗，抓到回歸':'回應碼通過，漏掉通知'):(v.cross&&v.effects?'反例失敗，抓到回歸':'反例涵蓋不完整'),(r===2?v.effects:v.cross&&v.effects)?'通過':'缺口'],['監控',v.monitor?'可追溯請求與副作用':'未規劃可追溯訊號',v.monitor?'通過':'缺口'],['應變',v.response?'有處理人與動作':'未指定處理方式',v.response?'通過':'缺口']];return result(rows.every(x=>x[2]==='通過'),rows,'刻意缺陷應讓反例測試失敗；修補版本應讓合法與拒絕案例符合需求。',[['定位',v.env==='target'?'正確環境與版本':'環境版本不符'],['重現與修補',v.repair?'拒絕發生在副作用之前':'拒絕發生得太晚'],['持續驗證',v.effects?'檢查資料與通知影響':'只看回應無法證明無副作用']]);}}
];
