export type Values=Record<string,string|boolean>;
export type Control={key:string;label:string;type:'select'|'check'|'text';options?:[string,string][];value:string|boolean;hint?:string};
export type Outcome={signature:string;title:string;tone:'good'|'bad'|'neutral';summary:string;trace:[string,string][];columns:string[];rows:string[][];code?:string;lesson:string};
export type Lab={title:string;story:string;mission:string;action:string;controls:Control[];source:string;limit:string;run:(v:Values)=>Outcome};
const select=(key:string,label:string,options:[string,string][],value=options[0][0]):Control=>({key,label,type:'select',options,value});
const check=(key:string,label:string,value=false):Control=>({key,label,type:'check',value});
const text=(key:string,label:string,value:string):Control=>({key,label,type:'text',value});
const authSource='https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html';
function request(v:Values):Outcome {
 const logged=v.actor!=='guest', own=v.actor===(v.case==='42'?'alice':'bob'), allowed=logged&&(!v.authz||own);
 if(v.channel==='ui'&&(!logged||!own))return {signature:'ui-hidden',title:'介面沒有送出請求',tone:'neutral',summary:'介面只顯示登入者自己的案件。改成直接呼叫 API，才能測試後端是否也有保護。',trace:[['前端顯示',logged?'這筆案件不在你的清單':'未登入，沒有案件清單'],['HTTP 請求','未送出'],['伺服器','尚未驗證後端規則']],columns:['案件','負責人','狀態'],rows:[],lesson:'前端不提供操作入口，無法證明後端會拒絕同樣的請求。切換為直接呼叫 API，觀察伺服器真正採用的規則。'};
 const status=!logged?'401':!allowed?'403':'200';
 return {signature:!logged?'anonymous':allowed&&!own?'leak':allowed?'owner':'blocked',title:`${status} ${!logged?'需要登入':!allowed?'拒絕存取':'回傳案件'}`,tone:allowed&&!own?'bad':allowed?'neutral':'good',summary:allowed?`回傳案件 ${v.case}；${own?'使用者是案件負責人。':'使用者不是案件負責人，發生越權讀取。'}`:'伺服器未回傳案件內容。',trace:[['請求入口',v.channel==='ui'?'由介面送出 HTTP 請求':'直接重送 HTTP 請求，沒有經過 UI'],['身分驗證',logged?`Session 對應 ${v.actor}`:'沒有有效 Session，回傳 401'],['權限驗證',!logged?'前一步停止':v.authz?(own?'案件負責人一致':'案件負責人不同，回傳 403'):'未檢查物件歸屬'],['資料回傳',allowed?'讀取案件的允許欄位':'未查詢案件內容']],columns:['案件','負責人','狀態'],rows:allowed?[[String(v.case),v.case==='42'?'alice':'bob','處理中']]:[],code:`GET /api/cases/${v.case} HTTP/1.1\nCookie: ${logged?`session=demo-${v.actor}`:'（未帶入）'}\n\nHTTP/1.1 ${status}\n${allowed?JSON.stringify({id:v.case,owner:v.case==='42'?'alice':'bob'}):'{ "error": "access denied" }'}`,lesson:'登入只確認身分。伺服器還必須逐次核對使用者與這筆案件的關係；請求由 UI 或工具送出，都適用同一套規則。'};
}
export const labs:Lab[]=[
{title:'同一筆案件，三種損害',story:'測試案件原本是「待處理」，只有承辦人可讀寫。你將模擬一個事件，查看資料、讀取對象與服務狀態。',mission:'觀察外洩、竄改、中斷，再啟用存取控制阻擋一次未授權存取。',action:'模擬事件',source:'https://www.nist.gov/cyberframework',limit:'此案例每個事件只凸顯一個主要影響；真實事件可能同時影響 CIA。',controls:[select('event','發生的事件',[['read','陌生人讀取案件'],['edit','陌生人修改案件狀態'],['outage','服務停止回應']]),check('guard','啟用伺服器存取控制')],run:v=>{const outage=v.event==='outage',blocked=!outage&&v.guard,impact=blocked?'無':outage?'A · 可用性':v.event==='edit'?'I · 完整性':'C · 機密性';return {signature:blocked?'blocked':String(v.event),title:blocked?'請求被拒絕':`受影響：${impact}`,tone:blocked?'good':'bad',summary:blocked?'陌生人無法讀取或修改案件。':outage?'承辦人也無法開啟案件。':v.event==='edit'?'案件被改成已結案，原始業務狀態遭破壞。':'案件內容出現在陌生人的回應中。',trace:[['事件',v.event==='read'?'陌生人讀取':v.event==='edit'?'陌生人修改':'服務中斷'],['保護措施',v.guard?'檢查使用者是否獲授權':'未啟用存取控制'],['結果',blocked?'拒絕未授權操作':outage?'存取控制無法讓停止的服務恢復':'未授權操作成功']],columns:['觀察項目','事件前','事件後'],rows:[['案件狀態','待處理',v.event==='edit'&&!blocked?'已結案':'待處理'],['陌生人取得內容','否',v.event==='read'&&!blocked?'是':'否'],['承辦人可使用','是',outage?'否':'是']],lesson:'保護措施要對應失敗原因。權限檢查處理存取問題，服務中斷還需要可用性與復原措施。'};}},
{title:'今天只能先修一個',story:'A：高嚴重度報表服務（CVSS 9.8）；B：案件 API（CVSS 7.5）。兩者都是虛構且已確認受影響的漏洞。調整 B 的實際部署條件。',mission:'讓 B 排到 A 前面，再讓 A 排回第一。比較每次排序的理由。',action:'重新排定修補順序',source:'https://www.first.org/epss/faq',limit:'教學採可解釋的排序規則，不計算通用風險分數；資料不是即時 CVE 或正式修補 SLA。',controls:[check('public','B 可從網際網路觸及'),check('kev','B 已確認在野利用（KEV 訊號）'),check('critical','B 承載核心案件業務'),select('epss','B 的 EPSS',[['low','1%'],['high','60%']])],run:v=>{const bFirst=!!v.public&&(!!v.kev||!!v.critical||v.epss==='high');const why=!v.public?'B 沒有直接對外暴露；本例先處理對外的 A。':v.kev?'B 對外且有已知利用證據。':v.critical?'B 對外且支撐核心業務。':v.epss==='high'?'B 對外且利用預測較高。':'兩者均對外；本例缺少額外急迫訊號，先修技術嚴重度較高的 A。';const a=['A 報表服務','9.8','對外／無 KEV／EPSS 1%','一般業務'];const b=['B 案件 API','7.5',`${v.public?'對外':'內網'}／${v.kev?'有':'無'} KEV／EPSS ${v.epss==='high'?'60%':'1%'}`,v.critical?'核心業務':'一般業務'];return {signature:bFirst?'B':'A',title:`優先處理 ${bFirst?'B 案件 API':'A 報表服務'}`,tone:'neutral',summary:why,trace:[['適用性','兩套服務都使用受影響版本'],['可達性',v.public?'A、B 都對外':'A 對外，B 僅內網'],['急迫性',why]],columns:['修補順位','服務','CVSS','利用與暴露','影響'],rows:(bFirst?[b,a]:[a,b]).map((r,i)=>[String(i+1),...r]),lesson:'CVSS 描述技術嚴重度；EPSS 是公開 CVE 未來 30 天在野利用的預測。排序還需納入暴露與業務影響，內網也不代表沒有風險。'};}},
{title:'你正在操作哪一台主機？',story:'本機和測試 VM 都有 logs/app.log，但內容不同。選擇連線，再執行指令，從輸出辨識你操作的環境。',mission:'在本機與測試 VM 各讀一次 logs/app.log，比較相同指令的輸出。',action:'執行模擬指令',source:'https://www.openssh.com/manual.html',limit:'這是唯讀虛擬終端，支援 pwd、ls、cat logs/app.log、whoami；不連線、不執行真實 Shell。',controls:[select('host','連線位置',[['local','本機'],['remote','SSH → 測試 VM']]),text('command','指令（pwd、ls、whoami、cat logs/app.log）','cat logs/app.log')],run:v=>{const remote=v.host==='remote',cwd=remote?'/srv/cases':'/home/learner/project',cmd=String(v.command).trim(),outputs:Record<string,string>={'pwd':cwd,'ls':'logs/  README.md','whoami':remote?'app-user':'learner','cat logs/app.log':remote?'[VM] API listening :3000\n[VM] request 42 → 403':'[LOCAL] dev server :5173\n[LOCAL] hot reload ready'};const found=Object.hasOwn(outputs,cmd);return {signature:found&&cmd==='cat logs/app.log'?String(v.host):'command',title:found?'指令執行完成':'此虛擬終端不支援這個指令',tone:'neutral',summary:`目前位置：${cwd}。${remote?'SSH 連線後，指令作用於遠端檔案系統。':'目前讀取的是本機開發檔案。'}`,trace:[['連線',remote?'透過 SSH 到測試 VM':'本機終端'],['工作目錄',cwd],['解析相對路徑',`${cwd}/logs/app.log`]],columns:['主機','使用者','工作目錄'],rows:[[remote?'test-vm':'local',remote?'app-user':'learner',cwd]],code:`${remote?'app-user@test-vm':'learner@local'} $ ${cmd}\n${outputs[cmd]??'支援：pwd、ls、whoami、cat logs/app.log'}`,lesson:'指令名稱相同，作用的主機、帳號和路徑可能不同。閱讀日誌前，先確認連線位置與工作目錄。'};}},
{title:'改變請求，觀察伺服器是否放行',story:'Alice 負責案件 42；Bob 負責案件 73。介面只列出自己的案件，你可以直接改變請求中的案件編號。',mission:'先用 Alice 讀取案件 42，再讀取 73 觀察外洩，最後啟用權限檢查拒絕同一請求。',action:'送出 HTTP 請求',source:authSource,limit:'本機模擬使用簡化的 Session 與 401／403 回應，沒有呼叫外部 API；實務也可能以 404 隱藏資源存在。',controls:[select('actor','登入身分',[['alice','Alice'],['bob','Bob'],['guest','未登入']]),select('case','請求案件',[['42','案件 42 · Alice'],['73','案件 73 · Bob']],'73'),select('channel','送出方式',[['direct','直接呼叫 API'],['ui','從介面送出']]),check('authz','後端檢查案件歸屬')],run:request},
{title:'搜尋文字怎麼變成查詢指令？',story:'練習用案件清單有三筆虛構案件。選擇查詢建構方式，再輸入一般文字或預設的測試字串，觀察回傳筆數。',mission:'先查詢 open 建立正常基準，再以測試字串比較拼接與參數化結果。',action:'執行虛擬查詢',source:'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html',limit:'只模擬預設字串的查詢語意，不是真正的 SQL 引擎，也不執行輸入內容。',controls:[select('query','搜尋內容',[['book','open'],['payload',"' OR '1'='1"]]),select('binding','查詢建構方式',[['concat','直接拼接字串'],['param','參數化查詢']])],run:v=>{const payload=v.query==='payload',unsafe=payload&&v.binding==='concat',q=payload?"' OR '1'='1":'open',rows=unsafe?[['42','open'],['73','closed'],['81','review']]:payload?[]:[['42','open']];return {signature:unsafe?'injected':payload?'literal':'normal',title:`回傳 ${rows.length} 筆資料`,tone:unsafe?'bad':'good',summary:unsafe?'輸入改變查詢條件，OR 條件恆為真。':payload?'整串輸入只作為參數值；沒有狀態完全相同的案件。':'查詢只命中狀態為 open 的案件。',trace:[['輸入',q],['查詢邊界',v.binding==='param'?'先固定 SQL 結構，再綁定資料值':'將輸入直接加入 SQL 文字'],['資料庫解讀',unsafe?'OR 條件參與查詢運算':'輸入作為要比對的案件狀態']],columns:['案件 ID','狀態'],rows,code:v.binding==='param'?`SELECT * FROM cases WHERE status = ?;\n參數：${JSON.stringify(q)}`:`SELECT * FROM cases WHERE status = '${q}';`,lesson:'安全重點是把指令結構和輸入資料分開。一般字串搜尋成功，無法證明特殊輸入也被安全處理。'};}},
{title:'只改一個欄位，重送同一個請求',story:'已攔到 Alice 查詢案件 42 的合法請求。固定 Session，只改 URL 的案件 ID，再比較前後回應。',mission:'先重送原請求，再只把案件改成 73，最後修補後端重送一次，留下三種證據。',action:'重送到虛擬測試站',source:'https://portswigger.net/web-security/access-control',limit:'這是 Repeater 操作概念的本機模擬，不連到真實網站或 Burp。',controls:[select('case','唯一修改欄位：案件 ID',[['42','42 · 原請求'],['73','73 · 另一人的案件']]),check('authz','測試站已修補物件權限檢查')],run:v=>request({...v,actor:'alice',channel:'direct'})},
{title:'把一句安全要求做成後端規則',story:'規格：只有案件負責人可更新狀態，狀態必須是 open 或 closed，稽核日誌不得記錄 Session。調整三個規則，執行固定測試組。',mission:'先執行未加保護的版本，再補齊三個規則，讓四項安全檢查全部通過。',action:'執行安全驗收',source:'https://owasp.org/www-project-application-security-verification-standard/',limit:'此驗收只涵蓋畫面列出的四個需求，不代表系統已全面安全。',controls:[check('owner','驗證案件負責人'),check('schema','只接受 open／closed'),check('redact','日誌遮蔽 Session')],run:v=>{const rows=[['合法負責人更新','200，狀態更新','通過'],['另一位使用者更新',v.owner?'403，狀態未變':'200，遭未授權修改',v.owner?'通過':'失敗'],['送入未知狀態',v.schema?'400，拒絕未知值':'200，寫入未知值',v.schema?'通過':'失敗'],['檢查稽核日誌',v.redact?'Session=[REDACTED]':'Session=demo-alice',v.redact?'通過':'失敗']];const failed=rows.filter(r=>r[2]==='失敗').length;return {signature:failed?'incomplete':'protected',title:`${4-failed} / 4 項通過`,tone:failed?'bad':'good',summary:failed?`還有 ${failed} 個需求未被落實。`:'這四項指定行為都有相對應的後端保護。',trace:[['規格','資源歸屬、狀態範圍、日誌機密'],['後端規則',`${[v.owner,v.schema,v.redact].filter(Boolean).length} / 3 項已啟用`],['驗收',failed?'測試揭露保護缺口':'固定測試組通過']],columns:['測試情境','實際結果','判定'],rows,lesson:'每個安全要求都要對應到具體規則及可執行的反例。成功更新的測試，只覆蓋合法路徑。'};}},
{title:'把保護放到資料跨界的位置',story:'檔案會從使用者經 Upload API、儲存區與解析器進入資料庫。挑一個威脅，在對應邊界配置保護，再觀察路徑在哪裡停止。',mission:'先觀察威脅通過，再配置有效保護，讓同一個威脅在對應邊界被攔下。',action:'推演資料流',source:'https://owasp.org/www-community/Threat_Modeling',limit:'精簡威脅模型，只推演三項指定威脅；未模擬所有檔案格式、解析漏洞與 STRIDE 類別。',controls:[select('threat','要推演的威脅',[['foreign','他人上傳到不屬於自己的案件'],['large','超大檔案耗盡解析資源'],['fields','解析內容含未允許欄位']]),check('upload','Upload API：核對案件歸屬'),check('parser','Parser：限制輸入大小與執行資源'),check('database','寫入前：驗證允許欄位')],run:v=>{const stop=v.threat==='foreign'?(v.upload?0:-1):v.threat==='large'?(v.parser?1:-1):(v.database?2:-1);const boundaries=['使用者 → Upload API','儲存區 → Parser','Parser → Database'];return {signature:stop<0?'exposed':'mitigated',title:stop<0?'威脅未被有效攔截':`在第 ${stop+1} 個邊界停止`,tone:stop<0?'bad':'good',summary:stop<0?(v.threat==='foreign'?'檔案被歸入別人的案件。':v.threat==='large'?'解析資源被耗盡，後續文件無法處理。':'不可信欄位進入案件資料。'):`${boundaries[stop]} 的保護對應到這次威脅。`,trace:boundaries.map((b,i)=>[b,stop===i?'攔截本次威脅':(stop>=0&&i>stop)||(v.threat==='large'&&stop<0&&i>1)?'未執行':i===1&&v.threat==='large'&&stop<0?'資源耗盡，處理失敗':'通過此邊界'] as [string,string]),columns:['邊界','已配置保護'],rows:[[boundaries[0],v.upload?'歸屬檢查':'無'],[boundaries[1],v.parser?'大小與資源限制':'無'],[boundaries[2],v.database?'欄位驗證':'無']],lesson:'保護要放在能確認條件的邊界。多加一項不相關的措施，不能替代真正缺少的檢查。'};}},
{title:'AI 改壞一條規則，CI 看得見嗎？',story:'新版程式可能漏掉歸屬檢查或狀態驗證。選擇這次改動及要執行的測試，觀察 CI 會放行、阻擋，還是漏掉問題。',mission:'讓有缺陷的改動通過一次，再加入能抓到它的測試，讓 CI 阻擋同一項改動。',action:'執行 CI 模擬',source:'https://owasp.org/www-project-samm/',limit:'以兩種刻意注入的缺陷示範測試覆蓋，不會呼叫真實 CI；通過不等於沒有其他漏洞。',controls:[select('mutation','這次程式改動',[['owner','刪除案件歸屬檢查'],['schema','刪除狀態驗證'],['none','保留所有規則']]),check('happy','執行：合法使用者可更新',true),check('cross','執行：不同負責人應被拒絕'),check('invalid','執行：未知狀態應被拒絕')],run:v=>{const rows=[['合法更新',!!v.happy,false],['跨帳號更新',!!v.cross,v.mutation==='owner'],['未知狀態',!!v.invalid,v.mutation==='schema']] as [string,boolean,boolean][];const detected=rows.some(r=>r[1]&&r[2]),count=rows.filter(r=>r[1]).length,bug=v.mutation!=='none';return {signature:!count?'empty':detected?'detected':bug?'missed':'clean',title:!count?'未執行任何測試':detected?'CI 阻擋這次改動':bug?'CI 綠燈，但缺陷漏掉了':'所選測試通過',tone:!count||bug&&!detected?'bad':'good',summary:!count?'沒有測試結果可作為發布證據。':detected?'反例測試命中了被刪除的保護。':bug?'所選測試沒有覆蓋這次被改壞的行為。':'本例沒有注入缺陷；測試保證仍僅限已選情境。',trace:[['程式變動',v.mutation==='owner'?'刪除案件歸屬檢查':v.mutation==='schema'?'刪除狀態驗證':'保留所有規則'],['執行範圍',`${count} 項測試`],['發布決策',!count?'不以空測試組作為放行證據':detected?'拒絕合併':'測試流程允許合併']],columns:['測試','是否執行','結果'],rows:rows.map(([name,on,fail])=>[name,on?'是':'否',!on?'未覆蓋':fail?'失敗':'通過']),lesson:'CI 只會依已寫入的斷言判斷。測試通過是指定行為的證據，增加能重現失敗的反例，才能約束後續改動。'};}}
];
export function initial(lab:Lab):Values{return Object.fromEntries(lab.controls.map(c=>[c.key,c.value]));}
export function achieved(id:number,signatures:string[]):boolean{const s=new Set(signatures);const need=[['read','edit','outage','blocked'],['A','B'],['local','remote'],['owner','leak','blocked'],['normal','injected','literal'],['owner','leak','blocked'],['incomplete','protected'],['exposed','mitigated'],['missed','detected']][id];return need.every(x=>s.has(x));}
