// Deterministic teaching models. No requests, SQL, shell commands or HTML are executed.
export type Status='ok'|'blocked'|'bad'|'skipped'|'info';
export type Event={node:string;label:string;detail:string;status:Status;data:string;effects?:{data:string;notice:string;response:string}};
export type Check={name:string;pass:boolean;expected:string;actual:string;node:string};
export type Result={events:Event[];checks:Check[];summary:string;safe:boolean;signature:string};
export type Config={actor:string;target:string;event:string;placements:Record<string,string>;known:string[];order:string[];routes:Record<string,string>;input:string;environment:string;log:string;command:string;commands:string[];tests:string[];fault:string;transaction:boolean;afterCommit:boolean;priority:string[]};
export type Node={id:string;label:string;kind:string;zone:string;hint:string};
export type Rule={id:string;label:string;hint:string};
export type Definition={title:string;mission:string;nodes:Node[];rules:Rule[];slots:string[];tasks:[string,string,string];limit:string};
const node=(id:string,label:string,kind:string,zone:string,hint:string):Node=>({id,label,kind,zone,hint});
const rule=(id:string,label:string,hint:string):Rule=>({id,label,hint});
export const definitions:Record<number,Definition>={
0:{title:'案件資產實驗室',mission:'選擇事件與保護位置，確認機密性、完整性與可用性受到什麼影響。',nodes:[node('client','事件來源','user','使用者','選擇想觀察的事件。'),node('api','案件服務','server','操作邊界','在資料被讀寫之前限制權限。'),node('data','案件資料','database','資產','觀察內容、狀態與可用性。'),node('recovery','備援服務','server','復原','此模型的備援可接手單一服務中斷。')],rules:[rule('access','存取控制','限制未授權讀寫，不處理服務中斷。'),rule('failover','故障切換','在備援服務接手中斷；不處理越權。')],slots:['api','data','recovery'],tasks:['不放保護，觀察未授權讀取。','保護案件讀寫，並確認合法存取。','保留存取控制，再處理服務中斷。'],limit:'固定案件與單一故障模型；故障切換不代表真實系統已具備完整災難復原。'},
7:{title:'文件邊界配置台',mission:'將檢查放到能判定條件的元件，再讓不同文件通過。',nodes:[node('client','文件來源','document','外部','可控制案件編號、大小與內容欄位。'),node('upload','Upload API','shield','上傳邊界','知道登入者與案件歸屬。'),node('parser','解析器','server','解析邊界','消耗記憶體與運算資源。'),node('data','資料寫入','database','欄位邊界','只接受允許更新的欄位。')],rules:[rule('owner','案件歸屬檢查','需在 Upload API 接受檔案前判定。'),rule('budget','解析資源限制','由解析器限制這個模型的資源耗用。'),rule('fields','允許欄位清單','在資料寫入前檢查解析出的欄位。')],slots:['upload','parser','data'],tasks:['不放保護，追蹤跨案件文件。','配置三道保護，驗證正常與異常文件。','改用超大文件，確認錯誤位置不能提供保護。'],limit:'僅涵蓋歸屬、大小與欄位三類威脅，不執行真實 PDF 解析。'},
1:{title:'漏洞證據與修補看板',mission:'先查證，再排列修補優先順序；缺少證據時保持未確認。',nodes:[node('advisory','漏洞公告','document','外部資訊','A：CVSS 9.8；B：CVSS 7.5。均為虛構漏洞。'),node('inventory','部署版本','server','受影響範圍','產品名稱相同，不代表版本受影響。'),node('exposure','暴露與利用','document','證據','查證網路可達性與已知利用。'),node('decision','修補佇列','shield','決策','排序需同時考慮影響與利用條件。')],rules:[],slots:[],tasks:['查看三份證據，判定情境一的優先順序。','重新查證情境二，調整修補順序。','第三份部署快照：辨識不受影響的服務。'],limit:'虛構部署與確定性教學排序，不接收即時 CVE、EPSS 或 KEV 資料。'},
3:{title:'身分與案件權限工作台',mission:'讓合法請求能讀取案件，並在回傳資料前攔下違規請求。',nodes:[node('client','瀏覽器 / API 工具','browser','用戶端','隱藏 UI 仍可被直接請求繞過。'),node('before','讀取之前','server','後端入口','可驗證 Session 和資源歸屬。'),node('data','案件資料','database','資料邊界','42 屬於 Alice；73 屬於 Bob。'),node('after','回傳之後','browser','資料已離開','此時拒絕已無法收回送出的資料。')],rules:[rule('ui','隱藏前端按鈕','只影響 UI；本工作台由 API 工具送出請求。'),rule('session','驗證身分','辨識登入者，拒絕無有效 Session 的請求。'),rule('owner','核對案件歸屬','在讀取前核對人與資源，防止越權。')],slots:['client','before','after'],tasks:['以 Alice 請求 Bob 的案件，觀察缺少規則的後果。','放好身分與歸屬檢查，重送相同請求。','改用未登入者，並執行完整合法／違規驗證。'],limit:'只模擬兩個使用者與讀取權限；不涵蓋 Session 竊取、過期與跨租戶。'},
4:{title:'SQL 與 HTML 雙路徑',mission:'同一份外部輸入進入兩種解讀環境，各自需要有效保護。',nodes:[node('input','外部輸入','document','輸入邊界','格式驗證與安全解讀是不同責任。'),node('sql','SQL 查詢','database','查詢路徑','參數化把資料值和查詢結構分開。'),node('html','HTML 顯示','browser','顯示路徑','輸出編碼讓文字不被當成標記。')],rules:[rule('validate','長度驗證','本模型僅限制長度，測試字串仍在允許長度內。'),rule('param','參數化查詢','配置在 SQL 路徑，固定查詢結構。'),rule('encode','HTML 輸出編碼','配置在 HTML 路徑，顯示字面文字。')],slots:['input','sql','html'],tasks:['使用測試輸入，觀察兩條路徑的風險。','保護 SQL 與 HTML，再重送相同輸入。','切換正常輸入，確認功能仍可用。'],limit:'SQL 與 HTML 都是固定字串的語意模型，不執行 SQL 或插入可執行 HTML；編碼只代表文字節點情境。'},
6:{title:'多入口與共用規則',mission:'把每條入口接到保護所在的位置，確保批次與背景工作也受約束。',nodes:[node('api','單筆 API','browser','入口一','入口規則只保護這條路徑。'),node('batch','批次匯入','document','入口二','可選擇通過共用服務或直接寫入。'),node('worker','背景工作','server','入口三','背景執行也需要業務條件檢查。'),node('shared','共用服務','shield','業務規則','只有實際經過的路徑會執行這裡的規則。'),node('data','案件資料與日誌','database','輸出','檢查狀態變更與敏感資料出口。')],rules:[rule('owner','資源授權','拒絕修改他人的案件。'),rule('state','狀態轉移','禁止重新修改已結案案件。'),rule('fields','欄位清單','拒絕外部指定管理員欄位。'),rule('redact','日誌遮罩','避免敏感值出現在操作日誌。')],slots:['api','shared'],tasks:['讓批次直接寫入，觀察越權。','讓所有入口經過共用保護，驗證五種情境。','使用背景工作修改已結案案件，確認不能繞過。'],limit:'三條固定入口與四項規則；未模擬其他 API、競態條件或服務間憑證。'},
2:{title:'環境與日誌調查台',mission:'先定位執行環境，再把請求配對到正確版本的日誌。',nodes:[node('terminal','終端工作階段','terminal','目前環境','切換環境後，指令紀錄會重新開始。'),node('service','部署服務','server','版本','測試目標會隨任務改變。'),node('logs','日誌來源','document','證據','選擇來源後，核對版本與請求識別。')],rules:[],slots:[],tasks:['調查測試 VM 的 v2 / R42，留下可追溯證據。','目標升級到 v3 / R99，避免沿用舊日誌。','辨識正式環境相同請求 ID，仍不能混用測試證據。'],limit:'支援 pwd、whoami、version 與 cat logs/app.log 的固定模擬，不連線主機或執行 shell。'},
5:{title:'請求重送與副作用時間線',mission:'調整檢查、寫入與通知順序，確認拒絕時沒有資料與通知副作用。',nodes:[node('authorize','權限檢查','shield','判定','合法請求允許；跨案件請求拒絕。'),node('write','寫入案件','database','資料','可在交易內暫存，最後提交或回滾。'),node('notify','寄送通知','document','副作用','已寄出的通知不能被資料庫回滾收回。'),node('response','送出回應','browser','回應','永遠在處理結束後回覆，不能拿狀態碼代替資料證據。')],rules:[],slots:[],tasks:['以跨案件請求觀察「403 但已有副作用」。','移動檢查到寫入之前，重送同一請求。','處理被鎖定的晚檢查流程：用交易與提交後通知消除副作用。'],limit:'固定操作的同步時間線；交易與通知策略是簡化模型，不保證真實訊息恰好一次投遞。'},
8:{title:'測試與缺陷驗證台',mission:'選擇測試，再刻意移除保護，確認測試真的能抓到對應缺陷。',nodes:[node('change','候選變更','document','程式','選擇刻意植入的缺陷。'),node('suite','回歸測試','branch','驗證','未選入的情境沒有測試證據。'),node('gate','發布閘門','shield','CI','測試失敗會阻擋發布；漏測仍可能綠燈。'),node('monitor','監控與處理','server','上線之後','指定異常訊號、處理人與回復動作。')],rules:[],slots:[],tasks:['只用合法測試，觀察權限缺陷漏測。','加入反例，讓 CI 抓到權限缺陷。','覆蓋狀態與副作用缺陷，並配置監控處理。'],limit:'測試只針對列出的固定缺陷；不能把通過率當成整體安全程度。'}
};
export function initialConfig(id:number,round=0):Config{return {actor:round===2&&id===3?'guest':'alice',target:'73',event:id===0?(round===2?'outage':'read'):id===7?(round===2?'large':'foreign'):id===6?(round===2?'closed':'foreign'):'read',placements:{},known:[],order:round===1&&id===5?['write','notify','authorize']:['write','notify','authorize'],routes:{api:'shared',batch:'direct',worker:'direct'},input:round===2&&id===4?'normal':'probe',environment:'local',log:'old',command:'pwd',commands:[],tests:['legal'],fault:round===2?'both':'owner',transaction:false,afterCommit:false,priority:['A','B']};}
export const evidenceCards=[{id:'version',title:'版本盤點'},{id:'exposure',title:'網路暴露與利用'},{id:'impact',title:'業務影響'}];
export function facts(round:number):Record<string,string>{return round===0?{version:'A 與 B 均為受影響版本。',exposure:'A 對外且已有利用證據；B 僅內網，未有利用證據。',impact:'A 與 B 都處理核心案件；A 尚無可行緩解。'}:round===1?{version:'A 與 B 均為受影響版本。',exposure:'A 已有隔離緩解；B 對外且有已知利用。',impact:'B 為核心案件入口，A 的緩解經確認有效；B 的暴露尚未獲得緩解。'}:{version:'A 已升級到不受影響版本；B 仍受影響。',exposure:'B 對外，已有利用證據。',impact:'B 處理核心資料；A 本次不需為此漏洞修補。'};}
export const environments:Record<string,{label:string;version:string;request:string;path:string;user:string}>={local:{label:'本機開發',version:'dev',request:'L01',path:'/Users/alice/project',user:'alice'},old:{label:'測試 VM 舊版',version:'v1',request:'R42',path:'/srv/cases-v1',user:'tester'},test:{label:'測試 VM v2',version:'v2',request:'R42',path:'/srv/cases-v2',user:'tester'},next:{label:'測試 VM v3',version:'v3',request:'R99',path:'/srv/cases-v3',user:'tester'},prod:{label:'正式環境',version:'v3',request:'R99',path:'/srv/cases',user:'service'}};
export function commandOutput(c:Config,cmd:string){const e=environments[c.environment]!;return cmd==='pwd'?e.path:cmd==='whoami'?e.user:cmd==='version'?`cases-api ${e.version} · ${e.label}`:`${e.label} | cases-api ${e.version} | request=${e.request} | 403`}
const evt=(node:string,label:string,detail:string,status:Status='info',data=''):Event=>({node,label,detail,status,data});
const check=(name:string,pass:boolean,expected:string,actual:string,node:string):Check=>({name,pass,expected,actual,node});
const result=(events:Event[],checks:Check[],summary:string,signature:string):Result=>({events,checks,summary,signature,safe:checks.every(c=>c.pass)});
export function replay(c:Config){
 let written=false,notified=false,rejected=false;const events:Event[]=[];const legal=c.target==='42';
 const add=(event:Event,final=false)=>events.push({...event,effects:{data:written?(c.transaction&&!final?'closed（交易內待提交）':'closed'):'open',notice:notified?'已寄出 1 則':'尚未寄出',response:final?(rejected?'403':'200'):'尚未回應'}});
 for(const step of c.order){
  if(rejected){add(evt(step,step==='write'?'寫入案件':step==='notify'?'寄送通知':'權限檢查','前一步拒絕，未執行。','skipped'));continue;}
  if(step==='authorize'){rejected=!legal;add(evt(step,'權限檢查',legal?'Alice 可以修改案件 42。':'Alice 不得修改案件 73。',legal?'ok':'blocked'));}
  if(step==='write'){written=true;add(evt(step,'寫入案件',c.transaction?'在交易內暫存 closed。':'立即把案件狀態改成 closed。',legal?'ok':'bad','狀態：open → closed'));}
  if(step==='notify'){notified=!c.afterCommit;add(evt(step,'通知',c.afterCommit?'通知排入提交後佇列，尚未寄出。':'通知已寄出，無法用資料回滾收回。',c.afterCommit?'info':legal?'ok':'bad'));}
 }
 if(rejected&&c.transaction&&written){written=false;add(evt('write','交易回滾','拒絕操作，撤回暫存變更。','ok','狀態：open'));}
 if(!rejected&&c.afterCommit){notified=true;add(evt('notify','提交後通知','交易成功後寄出通知。','ok'),true);}
 add(evt('response','HTTP 回應',rejected?'403；仍需核對資料與通知。':'200；操作完成。',rejected?'blocked':'ok',`資料=${written?'closed':'open'}；通知=${notified?1:0}`),true);
 return {written,notified,rejected,events};
}
export function evaluate(id:number,c:Config,round=0):Result{
 const p=c.placements;const e:Event[]=[];let checks:Check[]=[];
 if(id===0){const access=p.access==='api',recovery=p.failover==='recovery';const blocked=access&&c.event!=='outage';const damage=c.event==='outage'?!recovery:!access;e.push(evt('client','事件',c.event==='read'?'陌生人請求案件內容。':c.event==='edit'?'陌生人要求修改案件狀態。':'主服務中斷。','info'),evt('api','案件服務',blocked?'未授權操作被拒絕。':c.event==='outage'?'主服務無法回應。':'缺少有效的前置存取檢查。',blocked?'blocked':damage?'bad':'info'),evt('data','資產狀態',c.event==='read'?(damage?'案件內容已外洩。':'案件內容未外洩。'):c.event==='edit'?(damage?'狀態被改為 closed。':'狀態保持 open。'):(damage?'合法使用者無法使用。':'備援接手，合法使用者可使用。'),damage?'bad':'ok'));checks=[check('未授權讀取',access,'0 筆外洩',access?'0 筆':'1 筆','api'),check('未授權修改',access,'狀態不變',access?'open':'closed','api'),check('合法存取',true,'可以完成','可以完成','data')];if(round===2)checks.push(check('單一服務中斷',recovery,'可由備援服務處理',recovery?'備援接手':'無法使用','recovery'));return result(e,checks,damage?'這次事件已造成資產損害。':'這次事件的影響已被保護限制。',damage?'exposed':'protected');}
 if(id===7){const guards={foreign:p.owner==='upload',large:p.budget==='parser',fields:p.fields==='data'};const target=c.event==='foreign'?'upload':c.event==='large'?'parser':'data';let stopped=false;for(const n of definitions[7]!.nodes){if(n.id==='client'){e.push(evt('client','文件',c.event==='foreign'?'他人案件文件':c.event==='large'?'超大文件':'含管理員欄位的文件'));continue;}if(stopped)e.push(evt(n.id,n.label,'前一步停止，未執行。','skipped'));else if(n.id===target){const g=guards[c.event as keyof typeof guards];e.push(evt(n.id,n.label,g?'有效規則拒絕這份文件。':'此處沒有對應保護，威脅造成影響。',g?'blocked':'bad'));stopped=g||c.event==='large';}else e.push(evt(n.id,n.label,'繼續處理。','ok'));}checks=Object.entries(guards).map(([k,v])=>check(k==='foreign'?'跨案件上傳':k==='large'?'超大檔案':'管理員欄位',v,'在對應邊界拒絕',v?'已拒絕':'未攔截',k==='foreign'?'upload':k==='large'?'parser':'data'));checks.push(check('正常文件',true,'正常寫入','正常寫入','data'));return result(e,checks,guards[c.event as keyof typeof guards]?'文件在對應邊界被攔截。':'文件已造成未被保護的影響。',guards[c.event as keyof typeof guards]?'protected':'exposed');}
 if(id===1){const f=facts(round),all=evidenceCards.every(k=>c.known.includes(k.id)),wanted=round===0?'A':'B';for(const [i,k] of evidenceCards.entries())e.push(evt(['inventory','exposure','advisory'][i]!,k.title,c.known.includes(k.id)?f[k.id]!:'尚未查證。',c.known.includes(k.id)?'ok':'skipped'));e.push(evt('decision','排序',all?`目前優先 ${c.priority[0]}；證據支持 ${wanted}。`:'證據不足，不能確認這份排序。',all&&c.priority[0]===wanted?'ok':'bad'));checks=[check('證據完整',all,'查看三份證據',`${c.known.length} / 3`,'inventory'),check('排序有依據',all&&c.priority[0]===wanted,`優先 ${wanted}`,`優先 ${c.priority[0]}`,'decision')];return result(e,checks,all?(c.priority[0]===wanted?'這份排序有部署證據支持。':'請依目前部署條件調整排序。'):'仍有未查證資訊。',all&&c.priority[0]===wanted?'supported':'unknown');}
 if(id===3){const session=p.session==='before',owner=p.owner==='before';const anonymous=c.actor==='guest',own=(c.actor==='alice'&&c.target==='42')||(c.actor==='bob'&&c.target==='73');const deny=(session&&anonymous)||(owner&&!own);const late=!deny&&(p.owner==='after'&&!own||p.session==='after'&&anonymous);e.push(evt('client','API 請求',`${c.actor} → GET /cases/${c.target}；直接請求不經過 UI。`),evt('before','前置檢查',deny?'請求在讀取前被拒絕。':session?'身分有效；繼續檢查資源。':'沒有有效的身分檢查。',deny?'blocked':'info'),evt('data','案件讀取',deny?'未查詢案件內容。':`取得案件 ${c.target} 並回傳。`,deny?'skipped':own?'ok':'bad',deny?'0 筆':'1 筆'),evt('after','用戶端',deny?'沒有收到案件資料。':late?'資料已回傳；此時拒絕無法收回。':'收到案件內容。',deny?'ok':own?'ok':'bad'));checks=[check('合法使用者讀自己的案件',true,'200，1 筆','200，1 筆','data'),check('Alice 讀 Bob 的案件',owner,'讀取前拒絕，0 筆',owner?'拒絕，0 筆':'資料已回傳','before'),check('未登入者讀取',session,'身分檢查拒絕',session?'401，0 筆':'未在身分階段拒絕','before')];return result(e,checks,deny?'請求被拒絕，資料沒有回傳。':own?'合法操作成功。':'資料已外洩。',deny?'protected':own?'legal':'exposed');}
 if(id===4){const param=p.param==='sql',encode=p.encode==='html',probe=c.input==='probe';e.push(evt('input','輸入',probe?'SQL 測試值與 HTML 測試文字分別送入兩條路徑。':'正常搜尋 open，顯示 Alice。','info',probe?"SQL: open' OR '1'='1 | HTML: <b>案件</b>":'open / Alice'),evt('sql','SQL 路徑',param?'綁定參數，輸入維持資料用途。':'將輸入拼入查詢結構。',probe&&!param?'bad':'ok',probe?(param?'匹配 0 筆':'條件被改變，回傳 3 筆'):'回傳 1 筆'),evt('html','HTML 路徑',encode?'編碼後以字面文字顯示。':'輸入被當成 HTML 標記解讀（僅模擬）。',probe&&!encode?'bad':'ok',probe?(encode?'顯示文字 <b>案件</b>':'標記改變呈現；存在輸出邊界缺陷'):'顯示 Alice'));checks=[check('SQL 測試輸入',param,'輸入不改變查詢結構',param?'參數值':'改變條件','sql'),check('HTML 測試輸入',encode,'以字面文字顯示',encode?'文字':'標記','html'),check('正常輸入',true,'正常查詢與顯示','1 筆 / Alice','input')];return result(e,checks,param&&encode?'兩條路徑各有對應保護。':'仍有未保護的解讀邊界。',param&&encode?'protected':'exposed');}
 if(id===6){const entry=round===2?'worker':'batch';const has=(key:string,route:string)=>p[key]===route||(p[key]==='shared'&&c.routes[route]==='shared');const guard=c.event==='closed'?'state':c.event==='fields'?'fields':'owner';const safe=has(guard,entry);e.push(evt(entry,'操作入口',`${entry==='batch'?'批次匯入':'背景工作'}：${c.event==='closed'?'修改已結案案件':c.event==='fields'?'寫入管理員欄位':'修改他人的案件'}`),evt('shared','共用服務',c.routes[entry]==='shared'?(safe?'在共用路徑執行有效規則，拒絕。':'經過共用服務，但缺少對應規則。'):'直接寫入，未經共用服務。',c.routes[entry]!=='shared'?'skipped':safe?'blocked':'bad'),evt('data','資料與日誌',safe?'拒絕操作，資料保持原狀。':'違規操作已寫入。',safe?'ok':'bad'));checks=[check('合法單筆操作',true,'允許','允許','api'),...['api','batch','worker'].map(r=>check(`${r} 的業務規則`,['owner','state','fields'].every(k=>has(k,r)),'三條規則皆有效',['owner','state','fields'].filter(k=>has(k,r)).length+' / 3',r)),check('所有入口日誌', ['api','batch','worker'].every(r=>has('redact',r)),'無敏感值',['api','batch','worker'].every(r=>has('redact',r))?'已遮罩':'仍有敏感值','data')];return result(e,checks,safe?'這條路徑的違規操作已被拒絕。':'入口繞過或缺少必要規則。',safe?'protected':'exposed');}
 if(id===2){const expected=round===0?'test':'next',env=environments[c.environment]!,log=environments[c.log]!;const located=['pwd','whoami','version','cat logs/app.log'].every(cmd=>c.commands.includes(cmd));const match=c.environment===expected&&c.log===expected;e.push(evt('terminal','目前主機',`${env.label} · ${env.user} · ${env.path}`),evt('service','服務版本',`${env.version} / ${env.request}`,c.environment===expected?'ok':'bad'),evt('logs','選定日誌',`${log.label} / ${log.version} / ${log.request}`,match?'ok':'bad'));checks=[check('環境定位',located,'完成四個定位／讀取指令',`${c.commands.length} / 4`,'terminal'),check('目標部署',c.environment===expected,`${environments[expected]!.label}`,env.label,'service'),check('日誌對應',match,'主機、版本與請求一致',match?'一致':'來源不一致','logs')];return result(e,checks,match&&located?'這份證據可以追溯到目標部署。':'目前證據仍無法對應目標部署。',match&&located?'matched':'mismatch');}
 if(id===5){const r=replay(c);const illegal=replay({...c,target:'73'}),legal=replay({...c,target:'42'});checks=[check('合法操作',legal.written&&legal.notified&&!legal.rejected,'200、更新、1 則通知',`${legal.rejected?403:200} / ${legal.written?'closed':'open'} / ${+legal.notified}`,'response'),check('違規操作不改資料',!illegal.written&&illegal.rejected,'403，open',`${illegal.rejected?403:200} / ${illegal.written?'closed':'open'}`,'write'),check('違規操作不寄通知',!illegal.notified,'0 則',`${+illegal.notified} 則`,'notify')];return result(r.events,checks,r.rejected?(r.written||r.notified?'回應是 403，但仍有副作用。':'403；資料與通知都沒有副作用。'):'合法操作完成。',r.rejected?(r.written||r.notified?'side-effect':'protected'):'legal');}
 const active=c.fault==='both'?['state','side']:c.fault==='none'?[]:[c.fault];const tests=['legal','owner','state','side'];const names:Record<string,string>={legal:'合法更新',owner:'跨案件拒絕',state:'已結案拒絕',side:'拒絕後無副作用'};const caught=active.filter(f=>c.tests.includes(f));e.push(evt('change','植入缺陷',active.length?active.map(f=>names[f]).join('、')+' 的保護被移除。':'所有規則正常。'));for(const t of tests)e.push(evt('suite',names[t]!,!c.tests.includes(t)?'未選入測試，沒有證據。':active.includes(t)?'測試失敗，抓到缺陷。':'測試通過。',!c.tests.includes(t)?'skipped':active.includes(t)?'blocked':'ok'));e.push(evt('gate','CI 判定',caught.length?'有測試失敗，阻擋發布。':'所選測試通過。',caught.length?'blocked':active.length?'bad':'ok'));const monitor=c.placements.signal==='denied'&&c.placements.person==='oncall'&&c.placements.action==='investigate';checks=[check('正常版本不被誤擋',c.tests.includes('legal'),'合法測試有通過證據',c.tests.includes('legal')?'已驗證':'未測','suite'),check('刻意缺陷可被偵測',active.length>0&&caught.length===active.length,'每項缺陷都有反例',`${caught.length} / ${active.length}`,'gate')];if(round===2)checks.push(check('上線處理',monitor,'訊號、責任與處理方式完整',monitor?'已配置':'尚未完成','monitor'));return result(e,checks,caught.length===active.length&&active.length?'所選測試抓到了這次的全部缺陷。':active.length?'仍有缺陷未被測試抓到。':'這次沒有植入缺陷；不能用來證明反例的偵測力。',caught.length===active.length&&active.length?'detected':'missed');
}
export function accepted(id:number,round:number,c:Config,r:Result){if([1,2].includes(id))return r.safe;if(round===0)return id===8?r.signature==='missed'&&c.fault==='owner'&&c.tests.length===1&&c.tests[0]==='legal':id===5?r.signature==='side-effect'&&c.target==='73':r.signature==='exposed'&&(id!==0||c.event==='read')&&(id!==7||c.event==='foreign')&&(id!==3||c.actor==='alice'&&c.target==='73')&&(id!==4||c.input==='probe')&&(id!==6||c.event==='foreign');if(!r.safe)return false;if(id===0&&round===2)return c.event==='outage';if(id===7&&round===2)return c.event==='large';if(id===3)return round===2?c.actor==='guest':c.actor==='alice'&&c.target==='73';if(id===4)return c.input===(round===2?'normal':'probe');if(id===6&&round===2)return c.event==='closed';if(id===5)return c.target==='73'&&(round!==2||c.transaction&&c.afterCommit&&c.order.join(',')==='write,notify,authorize');if(id===8)return c.fault===(round===2?'both':'owner');return true;}
